# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  # - package-ecosystem: "npm" # See documentation for possible values
  #   directory: "frontend" # Location of package manifests
  #   reviewers:
  #     - "Zuricos"
  #   schedule:
  #     interval: "weekly"
  #     day: "sunday"
  #   groups:
  #     all:
  #       patterns:
  #         - "*"
  #   commit-message:
  #     prefix: "chore: NPM"
  #     include: "scope"
  #   ignore:
  #     - dependency-name: "*"
  #       update-types: ["version-update:semver-major"]
  - package-ecosystem: "nuget" # .NET NuGet packages
    directory: "backend" # Location of package manifests (root directory)
    reviewers:
      - "Zuricos"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      all:
        patterns:
          - "*"
    commit-message:
      prefix: "chore: NuGet"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]