// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zuricos.Folio.Data;

#nullable disable

namespace Zuricos.Folio.Api.Migrations
{
    [DbContext(typeof(FolioDbContext))]
    [Migration("20250514174924_InitEmpty")]
    partial class InitEmpty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");
#pragma warning restore 612, 618
        }
    }
}
