// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zuricos.Folio.Data;

#nullable disable

namespace Zuricos.Folio.Api.Migrations
{
    [DbContext(typeof(FolioDbContext))]
    partial class FolioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");
#pragma warning restore 612, 618
        }
    }
}
