name: folio
services:
  database:
    container_name: database
    image: postgres:17
    env_file: local-docker.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data_17:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres_data_17:

networks:
  default:
