// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zuricos.Folio.Data;

#nullable disable

namespace Zuricos.Folio.Migrations.Psql.Migrations
{
    [DbContext(typeof(FolioDbContext))]
    partial class FolioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zuricos.Folio.Data.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Accounts_Name");

                    b.HasIndex("PortfolioId", "Type", "IsDeleted")
                        .HasDatabaseName("IX_Accounts_PortfolioId_Type_IsDeleted");

                    b.HasIndex("UserId", "PortfolioId", "IsDeleted")
                        .HasDatabaseName("IX_Accounts_UserId_PortfolioId_IsDeleted");

                    b.ToTable("Accounts", t =>
                        {
                            t.HasCheckConstraint("CK_Accounts_DisplayCurrency_Format", "LENGTH(\"DisplayCurrency\") = 3 AND \"DisplayCurrency\" = UPPER(\"DisplayCurrency\")");

                            t.HasCheckConstraint("CK_Accounts_Name_NotEmpty", "LENGTH(TRIM(\"Name\")) > 0");

                            t.HasCheckConstraint("CK_Accounts_SoftDelete_Integrity", "(\"IsDeleted\" = false AND \"DeletedUtc\" IS NULL) OR (\"IsDeleted\" = true AND \"DeletedUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Accounts_Type_Valid", "\"Type\" IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("Zuricos.Folio.Data.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19, 4)");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("Fees")
                        .HasColumnType("numeric(19, 4)");

                    b.Property<decimal?>("FxRate")
                        .HasColumnType("numeric(18, 8)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(20, 8)");

                    b.Property<string>("SourceCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("numeric(19, 4)");

                    b.Property<Guid?>("TransferGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OccurredOn")
                        .HasDatabaseName("IX_Activities_OccurredOn");

                    b.HasIndex("TransferGroupId")
                        .HasDatabaseName("IX_Activities_TransferGroupId")
                        .HasFilter("\"TransferGroupId\" IS NOT NULL");

                    b.HasIndex("AssetId", "OccurredOn")
                        .HasDatabaseName("IX_Activities_AssetId_OccurredOn")
                        .HasFilter("\"AssetId\" IS NOT NULL");

                    b.HasIndex("AccountId", "OccurredOn", "IsDeleted")
                        .HasDatabaseName("IX_Activities_AccountId_OccurredOn_IsDeleted");

                    b.HasIndex("UserId", "Type", "OccurredOn")
                        .HasDatabaseName("IX_Activities_UserId_Type_OccurredOn");

                    b.ToTable("Activities", t =>
                        {
                            t.HasCheckConstraint("CK_Activities_Amount_Positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_Activities_Asset_Required_For_Securities", "(\"Type\" IN (4, 5) AND \"AssetId\" IS NOT NULL) OR \"Type\" NOT IN (4, 5)");

                            t.HasCheckConstraint("CK_Activities_Currency_Format", "LENGTH(\"Currency\") = 3 AND \"Currency\" = UPPER(\"Currency\")");

                            t.HasCheckConstraint("CK_Activities_Fees_NonNegative", "\"Fees\" IS NULL OR \"Fees\" >= 0");

                            t.HasCheckConstraint("CK_Activities_FxRate_Positive", "\"FxRate\" IS NULL OR \"FxRate\" > 0");

                            t.HasCheckConstraint("CK_Activities_MultiCurrency_Consistency", "(\"FxRate\" IS NULL AND \"SourceCurrency\" IS NULL) OR (\"FxRate\" IS NOT NULL AND \"SourceCurrency\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Activities_Quantity_NonNegative", "\"Quantity\" >= 0");

                            t.HasCheckConstraint("CK_Activities_SoftDelete_Integrity", "(\"IsDeleted\" = false AND \"DeletedUtc\" IS NULL) OR (\"IsDeleted\" = true AND \"DeletedUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Activities_SourceCurrency_Format", "\"SourceCurrency\" IS NULL OR (LENGTH(\"SourceCurrency\") = 3 AND \"SourceCurrency\" = UPPER(\"SourceCurrency\"))");

                            t.HasCheckConstraint("CK_Activities_Tax_NonNegative", "\"Tax\" IS NULL OR \"Tax\" >= 0");

                            t.HasCheckConstraint("CK_Activities_Type_Valid", "\"Type\" IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 99)");
                        });
                });

            modelBuilder.Entity("Zuricos.Folio.Data.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("DataSource")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DataSource")
                        .HasDatabaseName("IX_Assets_DataSource");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("IX_Assets_Symbol_Unique");

                    b.HasIndex("Currency", "IsDeleted")
                        .HasDatabaseName("IX_Assets_Currency_IsDeleted");

                    b.HasIndex("Symbol", "Currency")
                        .HasDatabaseName("IX_Assets_Symbol_Currency");

                    b.HasIndex("UserId", "IsDeleted")
                        .HasDatabaseName("IX_Assets_UserId_IsDeleted");

                    b.ToTable("Assets", t =>
                        {
                            t.HasCheckConstraint("CK_Assets_Currency_Format", "LENGTH(\"Currency\") = 3 AND \"Currency\" = UPPER(\"Currency\")");

                            t.HasCheckConstraint("CK_Assets_ISIN_Format", "LENGTH(\"Isin\") <= 12 AND \"Isin\" ~ '^[A-Z]{2}[A-Z0-9]{9}[0-9]{1}$'");

                            t.HasCheckConstraint("CK_Assets_Name_NotEmpty", "LENGTH(TRIM(\"Name\")) > 0");

                            t.HasCheckConstraint("CK_Assets_SoftDelete_Integrity", "(\"IsDeleted\" = false AND \"DeletedUtc\" IS NULL) OR (\"IsDeleted\" = true AND \"DeletedUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Assets_Symbol_NotEmpty", "LENGTH(TRIM(\"Symbol\")) > 0");
                        });
                });

            modelBuilder.Entity("Zuricos.Folio.Data.Models.AssetHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("AdjustedClose")
                        .HasColumnType("numeric(19, 4)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric(19, 4)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric(19, 4)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric(19, 4)");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric(19, 4)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric(20, 8)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "Date")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AssetHistories_AssetId_Date_Desc");

                    b.HasIndex("Date", "IsDeleted")
                        .HasDatabaseName("IX_AssetHistories_Date_IsDeleted");

                    b.HasIndex("AssetId", "Date", "IsDeleted")
                        .IsUnique()
                        .HasDatabaseName("IX_AssetHistories_AssetId_Date_Unique");

                    b.ToTable("AssetHistories", t =>
                        {
                            t.HasCheckConstraint("CK_AssetHistories_High_Low_Relationship", "\"High\" >= \"Low\"");

                            t.HasCheckConstraint("CK_AssetHistories_OHLC_Positive", "\"Open\" > 0 AND \"High\" > 0 AND \"Low\" > 0 AND \"Close\" > 0 AND \"AdjustedClose\" > 0");

                            t.HasCheckConstraint("CK_AssetHistories_OHLC_Range", "\"Open\" BETWEEN \"Low\" AND \"High\" AND \"Close\" BETWEEN \"Low\" AND \"High\"");

                            t.HasCheckConstraint("CK_AssetHistories_SoftDelete_Integrity", "(\"IsDeleted\" = false AND \"DeletedUtc\" IS NULL) OR (\"IsDeleted\" = true AND \"DeletedUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_AssetHistories_Volume_NonNegative", "\"Volume\" >= 0");
                        });
                });

            modelBuilder.Entity("Zuricos.Folio.Data.Models.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Institution")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Portfolios_Name");

                    b.HasIndex("UserId", "IsDeleted")
                        .HasDatabaseName("IX_Portfolios_UserId_IsDeleted");

                    b.HasIndex("UserId", "Institution", "IsDeleted")
                        .HasDatabaseName("IX_Portfolios_UserId_Institution_IsDeleted");

                    b.ToTable("Portfolios", t =>
                        {
                            t.HasCheckConstraint("CK_Portfolios_DisplayCurrency_Format", "LENGTH(\"DisplayCurrency\") = 3 AND \"DisplayCurrency\" = UPPER(\"DisplayCurrency\")");

                            t.HasCheckConstraint("CK_Portfolios_Name_NotEmpty", "LENGTH(TRIM(\"Name\")) > 0");

                            t.HasCheckConstraint("CK_Portfolios_SoftDelete_Integrity", "(\"IsDeleted\" = false AND \"DeletedUtc\" IS NULL) OR (\"IsDeleted\" = true AND \"DeletedUtc\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Zuricos.Folio.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("Theme")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrency")
                        .HasDatabaseName("IX_Users_BaseCurrency");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_BaseCurrency_Format", "LENGTH(\"BaseCurrency\") = 3 AND \"BaseCurrency\" = UPPER(\"BaseCurrency\")");

                            t.HasCheckConstraint("CK_Users_Language_Format", "\"Language\" ~ '^[a-z]{2}(-[A-Z]{2})?$'");

                            t.HasCheckConstraint("CK_Users_Theme_Valid", "\"Theme\" IN (0, 1, 2)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            BaseCurrency = "USD",
                            Language = "en-US",
                            Theme = 0
                        });
                });

            modelBuilder.Entity("Zuricos.Folio.Data.Models.Account", b =>
                {
                    b.HasOne("Zuricos.Folio.Data.Models.Portfolio", "Portfolio")
                        .WithMany("Accounts")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zuricos.Folio.Data.Models.User", null)
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Zuricos.Folio.Data.Models.Activity", b =>
                {
                    b.HasOne("Zuricos.Folio.Data.Models.Account", "Account")
                        .WithMany("Activities")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zuricos.Folio.Data.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Zuricos.Folio.Data.Models.User", null)
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Zuricos.Folio.Data.Models.AssetHistory", b =>
                {
                    b.HasOne("Zuricos.Folio.Data.Models.Asset", "Asset")
                        .WithMany("History")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Zuricos.Folio.Data.Models.Portfolio", b =>
                {
                    b.HasOne("Zuricos.Folio.Data.Models.User", null)
                        .WithMany("Portfolios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zuricos.Folio.Data.Models.Account", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Zuricos.Folio.Data.Models.Asset", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("Zuricos.Folio.Data.Models.Portfolio", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Zuricos.Folio.Data.Models.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Activities");

                    b.Navigation("Portfolios");
                });
#pragma warning restore 612, 618
        }
    }
}
